title: SCCS
description: > 
  The Swarthmore College Computer Society (SCCS) is a student-run group offering 
  computing services, tools, toys, and information to the Swarthmore College 
  community. 
  url: "http://sccs.swarthmore.edu" 
  baseurl: "/sccs-new-home/" # TODO: Remove this
  destination: "~/Desktop"

# CSS stuff
sass:
  sass_dir: _scss
  style: :compressed
